services:
  traefik:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    restart: always
    #env_file: .env
    command: 
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.websecure.address=:443"
      #- "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.email=`demo@gmail.com`"
      #- "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      #- "443:443"
      # The Web UI (enabled by --api.insecure=true)
      #- "8080:8080"
    networks:
      - traefik-network
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.traefik-http.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.traefik-http.entrypoints=web"
      - "traefik.http.routers.traefik-http.service=traefik"

      # https
      #- "traefik.http.routers.traefik-https.rule=Host(`traefik.example.com`)"
      #- "traefik.http.routers.traefik-https.entrypoints=websecure"
      #- "traefik.http.routers.traefik-https.tls.certresolver=myresolver"
      #- "traefik.http.routers.traefik-https.service=traefik"
      #- "traefik.http.routers.traefik-https.middlewares=gzip"

      # services
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

      # middlewares
      #- "traefik.http.middlewares.traefik-redirect.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.traefik-redirect.redirectscheme.permanent=true"
      #- "traefik.http.routers.traefik-http.middlewares=traefik-redirect"
      - "traefik.http.middlewares.gzip.compress=true"            

networks:
  traefik-network:
    external: true