FROM odoo:17.0

# change to the root user
USER root
#RUN apt-get update 
#RUN apt-get install -y pkg-config libxml2-dev libxmlsec1-dev libxmlsec1-openssl python3-pip python3-qrcode git nano
#RUN apt-get install -y gcc python3-dev
#RUN apt-get install -y python3-wheel
#RUN pip3 install xmlsec
#RUN pip3 install openpyxl odoo-test-helper openupgradelib
#RUN chown odoo:odoo /etc/odoo/odoo.conf
USER odoo
